### ISSUE TITLE
podmigration created but new pod ExitCode:0 after migrated

### ISSUE THREAD

**Issue by xyc-grace** [SSU-DCN/podmigration-operator#10]
Hi, I followed your steps in [init-cluster-containerd-CRIU.md](https://github.com/SSU-DCN/podmigration-operator/blob/main/init-cluster-containerd-CRIU.md) to install each component and started kubernetes service. I started the API server by running "go run ./api-server/cmd/main.go" and  the Podmigration operator by "make run".  And then I tried to migration pod from node "bb05" to node "bb04". Here are my steps:
1. I created pod on "bb05" by running "kubectl apply -f 2.yaml" and created podmigration object through "kubectl apply -f test2.yaml". 
2. Then the Podmigration operator detected this and started migrating pod according to my configuration. 
3. The old pod was terminated normally on "bb05", but the new pod status is "CreatingContainer" firstly and  becomes "ExitCode:0" finally. 

![image](https://user-images.githubusercontent.com/83322359/183273409-23b846bd-147b-495e-acd6-44830bf60150.png)

System info for all nodes (same as your tutorial):
* OS version #91~18.04.1-Ubuntu
* kubenetes version: v1.19.0-beta.0.1012+a01322acadbe97
* containerd version: containerd github.com/containerd/containerd 4e2f2014-TEST
* kubeadm version: &version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-beta.0.1012+a01322acadbe97", GitCommit:"a01322acadbe978190388c66d5159eb55072a144", GitTreeState:"clean", BuildDate:"2022-08-01T05:59:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
* runc version runc version 1.0.0-rc92
* criu version Version: 3.14
* nfs works normally

**I wonder why the new pod is not migrated successfully as "Running" status.**  Waiting for your help. Thanks!

**Comment by xyc-grace** [comment]
Worthy to mention that I got log on dest node, and it seems that containerd had received command to create pod, but kubelet lacks of "RestoreContainer" service. Does it indicates I have some components with wrong version?  And does my /etc/containerd/config.toml is wrong? Could you please give me a full example of your /etc/containerd/config.toml?

1. log of kubelet
journalctl -xfu kubelet
-- Logs begin at Mon 2022-08-08 00:35:45 UTC. --
Aug 08 03:19:42 bb05 kubelet[4255]: I0808 03:19:42.453703    4255 kuberuntime_manager.go:842] Should we migrate?Runningtrue
Aug 08 03:19:44 bb05 kubelet[4255]: E0808 03:19:44.604626    4255 remote_runtime.go:306] RestoreContainer "77c7401bc4e439cbb7c97683804eaf43a978a776f2cd7fa986490c6e5fdd5d24" from runtime service failed: rpc error: code = Unimplemented desc = unknown method RestoreContainer for service runtime.v1alpha2.RuntimeService
Aug 08 03:19:55 bb05 kubelet[4255]: I0808 03:19:55.005534    4255 kuberuntime_manager.go:842] Should we migrate?Runningfalse
Aug 08 03:20:05 bb05 kubelet[4255]: I0808 03:20:05.005630    4255 kuberuntime_manager.go:842] Should we migrate?Runningfalse
Aug 08 03:20:17 bb05 kubelet[4255]: I0808 03:20:17.005554    4255 kuberuntime_manager.go:842] Should we migrate?Runningfalse
Aug 08 03:20:42 bb05 kubelet[4255]: I0808 03:20:42.111679    4255 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 51555eb8a55c7ba8b074daf788943872ef48cfbd909eded08df12237beba87b5
Aug 08 03:20:42 bb05 kubelet[4255]: W0808 03:20:42.549208    4255 pod_container_deletor.go:79] Container "51555eb8a55c7ba8b074daf788943872ef48cfbd909eded08df12237beba87b5" not found in pod's containers
Aug 08 03:20:42 bb05 kubelet[4255]: I0808 03:20:42.549556    4255 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 77c7401bc4e439cbb7c97683804eaf43a978a776f2cd7fa986490c6e5fdd5d24
Aug 08 03:20:42 bb05 kubelet[4255]: I0808 03:20:42.549679    4255 kuberuntime_manager.go:842] Should we migrate?Runningtrue
Aug 08 03:20:44 bb05 kubelet[4255]: E0808 03:20:44.694853    4255 remote_runtime.go:306] RestoreContainer "2aa868bd32efca780ce95bf81415c390ca280665c453a2566b39cee9b2fdbce2" from runtime service failed: rpc error: code = Unimplemented desc = unknown method RestoreContainer for service runtime.v1alpha2.RuntimeService
Aug 08 03:21:16 bb05 kubelet[4255]: I0808 03:21:16.005856    4255 kuberuntime_manager.go:842] Should we migrate?Runningfalse
Aug 08 03:21:21 bb05 kubelet[4255]: I0808 03:21:21.005858    4255 kuberuntime_manager.go:842] Should we migrate?Runningfalse

2. log of containerd
Aug 08 03:22:44 bb05 containerd[25162]: time="2022-08-08T03:22:44.814374867Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for container &ContainerMetadata{Name:count,Attempt:9,}"
Aug 08 03:22:44 bb05 containerd[25162]: time="2022-08-08T03:22:44.904580568Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for &ContainerMetadata{Name:count,Attempt:9,} returns container id \"b4d29e1d56a1a09421d8
Aug 08 03:23:42 bb05 containerd[25162]: time="2022-08-08T03:23:42.182612466Z" level=info msg="RemoveContainer for \"208d2c5b51e9bfcfb99e8b73f67ddfe70d5dc01c6b564e863c64bb3198b7b56e\""
Aug 08 03:23:42 bb05 containerd[25162]: time="2022-08-08T03:23:42.195159755Z" level=info msg="RemoveContainer for \"208d2c5b51e9bfcfb99e8b73f67ddfe70d5dc01c6b564e863c64bb3198b7b56e\" returns successfully"
Aug 08 03:23:42 bb05 containerd[25162]: time="2022-08-08T03:23:42.811156028Z" level=info msg="PullImage \"alpine:latest\""
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.837896918Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.846783548Z" level=info msg="ImageUpdate event &ImageUpdate{Name:sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.851177960Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.855534669Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine@sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872,Labels:map[string]string{io.cri-containerd.image: manage
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.856049205Z" level=info msg="PullImage \"alpine:latest\" returns image reference \"sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53\""
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.857777328Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for container &ContainerMetadata{Name:count,Attempt:10,}"
Aug 08 03:23:44 bb05 containerd[25162]: time="2022-08-08T03:23:44.940792313Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for &ContainerMetadata{Name:count,Attempt:10,} returns container id \"e826d1ae5829c17bfd8
Aug 08 03:24:42 bb05 containerd[25162]: time="2022-08-08T03:24:42.199241568Z" level=info msg="RemoveContainer for \"b4d29e1d56a1a09421d824cc27a032c8e00c8af84c06936445259ff6031e6156\""
Aug 08 03:24:42 bb05 containerd[25162]: time="2022-08-08T03:24:42.211515138Z" level=info msg="RemoveContainer for \"b4d29e1d56a1a09421d824cc27a032c8e00c8af84c06936445259ff6031e6156\" returns successfully"
Aug 08 03:24:42 bb05 containerd[25162]: time="2022-08-08T03:24:42.898991038Z" level=info msg="PullImage \"alpine:latest\""
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.957583266Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.967941399Z" level=info msg="ImageUpdate event &ImageUpdate{Name:sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.973787314Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.979006483Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine@sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872,Labels:map[string]string{io.cri-containerd.image: manage
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.979466316Z" level=info msg="PullImage \"alpine:latest\" returns image reference \"sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53\""
Aug 08 03:24:44 bb05 containerd[25162]: time="2022-08-08T03:24:44.980784909Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for container &ContainerMetadata{Name:count,Attempt:11,}"
Aug 08 03:24:45 bb05 containerd[25162]: time="2022-08-08T03:24:45.081683057Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for &ContainerMetadata{Name:count,Attempt:11,} returns container id \"562783318d7fcbf5e33
Aug 08 03:25:42 bb05 containerd[25162]: time="2022-08-08T03:25:42.214483451Z" level=info msg="RemoveContainer for \"e826d1ae5829c17bfd8b4519c1fa74a78e8162156d52dd94d6643ff4e34ccdce\""
Aug 08 03:25:42 bb05 containerd[25162]: time="2022-08-08T03:25:42.226907731Z" level=info msg="RemoveContainer for \"e826d1ae5829c17bfd8b4519c1fa74a78e8162156d52dd94d6643ff4e34ccdce\" returns successfully"
Aug 08 03:25:42 bb05 containerd[25162]: time="2022-08-08T03:25:42.984678472Z" level=info msg="PullImage \"alpine:latest\""
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.961225284Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.970801862Z" level=info msg="ImageUpdate event &ImageUpdate{Name:sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.975936726Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.981726736Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine@sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872,Labels:map[string]string{io.cri-containerd.image: manage
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.982134364Z" level=info msg="PullImage \"alpine:latest\" returns image reference \"sha256:d7d3d98c851ff3a95dbcb70ce09d186c9aaf7e25d48d55c0f99aae360aecfd53\""
Aug 08 03:25:44 bb05 containerd[25162]: time="2022-08-08T03:25:44.984696246Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for container &ContainerMetadata{Name:count,Attempt:12,}"
Aug 08 03:25:45 bb05 containerd[25162]: time="2022-08-08T03:25:45.065628075Z" level=info msg="CreateContainer within sandbox \"b20621e33157915efd6fda14d47d4a7fb15dbd311df331d4596fa5662b356475\" for &ContainerMetadata{Name:count,Attempt:12,} returns container id \"fd1d171cbfa90c26a16

3. log of controller
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "print test": {"sourcePod":"simple","destHost":"bb05","selector":{"matchLabels":{"podmig":"dcn"}},"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[]}},"action":"live-migration"}}
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "annotations ": ""}
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "number of existing pod ": 0}
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "desired pod ": {"namespace": "default", "name": ""}}
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "number of desired pod ": 0}
2022-08-08T03:15:20.417Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "number of actual running pod ": 0}
2022-08-08T03:15:20.438Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 1 - Check source pod is exist or not - completed"}
2022-08-08T03:15:20.438Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "sourcePod ok ": {"apiVersion": "v1", "kind": "Pod", "namespace": "default", "name": "simple"}}
2022-08-08T03:15:20.438Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "sourcePod status ": "Running"}
2022-08-08T03:15:20.441Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 2 - checkpoint source Pod - completed"}
2022-08-08T03:15:20.441Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "live-migration pod": "count"}
2022-08-08T03:15:20.441Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "checkpointPath/var/lib/kubelet/migration/kkk/simple"}
2022-08-08T03:15:20.441Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 3 - Wait until checkpoint info are created - completed"}
2022-08-08T03:15:20.448Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 4 - Restore destPod from sourcePod's checkpointed info - completed"}
2022-08-08T03:15:27.257Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 4.1 - Check whether if newPod is Running or not - completedsimple-migration-62Running"}
2022-08-08T03:15:27.257Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 4.1 - Check whether if newPod is Running or not - completed"}
2022-08-08T03:15:27.261Z	INFO	controllers.Podmigration		{"podmigration": "default/simple-migration-controller-33", "Live-migration": "Step 6 - Delete the source pod - completed"}
2022-08-08T03:15:27.261Z	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "podmig.dcn.ssu.ac.kr", "reconcilerKind": "Podmigration", "controller": "podmigration", "name": "simple-migration-controller-33", "namespace": "default"}

**Comment by vutuong** [comment]
Hi @Grace-wondering-around 
I noticed that the kubelet raise the problem that "Unimplemented desc = unknown method RestoreContainer for service runtime.v1alpha2.RuntimeService"
This method should be existed with the custom kubelet and containerd-cri. Please check out again that the default binary of kubelet and containerd-cri are replaced with extended binary. For containerd-cri, please try approach 1. Build from source or 2. Download binaries at the Step 1 in the document.

If you still can not make it work by installing it manually . You may try the script that automate my document from:
https://gitlab.com/mindhappyokk/pod-migrating
