### ISSUE TITLE
Multi cluster migration

### ISSUE THREAD

**Issue by Minninnewah** [SSU-DCN/podmigration-operator#12]
Hi

I got the single-cluster version of this GitHub repository working and like to extend the scope to the multi-cluster version.
To set up the K8s cluster the README.md also reference the same files as in the single-cluster version. But If I check the file in the multi-cluster branch then at least the used containerd version is different. Additionally, I couldn't find any other information if I need to use the multi-cluster or main branch to set up the cluster.

As far as I can see from the commit most of the parts (like the kubelet plugins, the operator as well as the API server) has to be changed and therefore for the setup of the cluster as well as for the commands to setup the podmigration-operator I should use the files in this branch, is this correct?

**Comment by vutuong** [comment]
Hi @Minninnewah,
Hmm, my labmate did not update ```multi-cluster``` branch. I will ask him to push the lastest one. 
You need to build and use kubectl-plugin command from the ```multi-cluster```. Then you also need to run the podmigration-controller and api-server from this repo.
No need to change kubelet. 
Note: remember to change line in this function https://github.com/SSU-DCN/podmigration-operator/blob/9b2214edbc6ab51bcfa82dc4a91b3b222cb9e3cf/kubectl-plugin/migrate-command/migrate_command.go#L262 to your ip address before build the kubectl command.
