### ISSUE TITLE
How to do passive migration？

### ISSUE THREAD

**Issue by 120L020314** [SSU-DCN/podmigration-operator#17]
According to the description in your paper, this studio supports passive migration, how do you trigger a passive migration?i have finished active migration，but how to migration when the pod fails. sorry  to disturb，thank you for teaching！ @vutuong @nezytic59

**Comment by vutuong** [comment]
@120L020314 Which paper are you mentioning?

**Comment by 120L020314** [comment]
@vutuong In the paper of Migrating Pods in Kubernetes,i mention this part:
The controller has to take care of creating a Pod when a MigratingPod is frist created and
of migrating the Pod whenever it gets deleted. In order to react to deletion it uses Finalizers
to prevent the Pod from being deleted right away. For the prototype, the controller was implemented following the operator pattern, which will be explained briely before describing
how the migration operator works.
and if "The controller has to take care of creating a Pod when a MigratingPod is frist created and
of migrating the Pod whenever it gets deleted." means when pod gets deleted ,it will be migrated passive? thank you,but i don't know my understanding is correct or wrong.
